"""Configuracion central editable para la version docente de FlapPyBird."""

# ===== VENTANA =====
SCREEN_WIDTH = 288
SCREEN_HEIGHT = 512
FPS = 30

# ===== MOVIMIENTO DEL PAJARO =====
GRAVITY = 1.0
JUMP_STRENGTH = -9.0
MAX_FALL_SPEED = 10.0
MIN_RISE_SPEED = -8.0

# ===== TUBOS Y DIFICULTAD =====
PIPE_SPEED = 5
PIPE_GAP = 120
DIFFICULTY_STEP_POINTS = 10
DIFFICULTY_GAP_REDUCTION = 4
DIFFICULTY_MIN_GAP = 90
DIFFICULTY_SPEED_INCREASE = 0.25

# ===== PUNTAJE Y VIDAS =====
SCORE_PER_PIPE = 1
START_LIVES = 1

# ===== ESCROLLEO VISUAL =====
BACKGROUND_SCROLL_SPEED = 4

# ===== DEBUG =====
DEBUG = False
